Footer modal
nadiakhoptiuk/filmoteka_project pull request #13
Opened 2022-06-17 09:50 UTC by VollDeMarr

2022-06-17 11:25 UTC, nadiakhoptiuk requested changes

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +          <h3 class="card-info__title">Volodymyr Bobanych</h3>
зроби p, будь ласка

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +                href="https://github.com/VollDeMarr"
aria-label додай

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +                href="https://www.linkedin.com/in/volodymyrbobanych/"
aria-label додай

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +          <h3 class="card-info__title">Volodymyr Bobanych</h3>
р

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +                href="https://www.linkedin.com/in/volodymyrbobanych/"
aria-label додай

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/partials/modal_footer.html
> +                href="https://github.com/VollDeMarr"
aria-label додай

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/sass/layout/_modal_footer.scss
> +  background-color: #ffffff;
var ()

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/sass/layout/_modal_footer.scss
> +  display: inline-block;
block

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/sass/layout/_modal_footer.scss
> +  border: 1px solid rgba(73, 68, 68, 0.3);
border ми ж прибираємо

2022-06-17 11:25 UTC, nadiakhoptiuk commented on src/sass/layout/_modal_footer.scss
> +  border: 1px solid var(--accent-text-color);
і тут

2022-06-20 10:34 UTC, nadiakhoptiuk requested changes

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/js/modal-close.js
> +  refs.body.classList.toggle('hidden');
-

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/js/refs.js
> +  closeBtn: document.querySelector('.close-footer-modal'),
назви

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/js/footer-modal.js
> +refs.btn.addEventListener('click', onClick);
слухачі потрібно перенести в індекс, і функції імпортувати з файла, який ти створиш для них

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/js/footer-modal.js
> +refs.btn.addEventListener('click', onClick);
цього файла у тебе виходить не буде

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/js/footer-modal.js
> +refs.modalDevBtn.addEventListener('click', onModalOpen);
слухачі переносимо в індекс і імпортуємо функції з файла, який ти створиш. цього не буде файла

2022-06-20 10:34 UTC, nadiakhoptiuk commented on src/sass/layout/_modal_footer.scss
> +.modal {
тут клас специфічний зроби

2022-06-20 10:52 UTC, VollDeMarr commented on src/js/refs.js
> +  closeBtn: document.querySelector('.close-footer-modal'),
btn -> modalDevBtn
closeBtn -> closeModalDevBtn

2022-06-20 11:01 UTC, VollDeMarr commented on src/sass/layout/_modal_footer.scss
> +.modal {
Готово

2022-06-20 12:44 UTC, merged